name: PyInstaller Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  pyinstaller-windows-x64-build:
    runs-on: <windows-latest / ubuntu-latest / ..... etc>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          python_arch: 'x64'
          pyinstaller_ver: '==6.11.1'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'MihoyoBBSTools'
          options: --onefile, --name "MihoyoBBSTools"

  pyinstaller-linux-arm64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          python_arch: 'arm64'
          pyinstaller_ver: '==6.11.1'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'MihoyoBBSTools'
          options: --onefile, --name "MihoyoBBSTools"

  pyinstaller-linux-amd64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          python_arch: 'amd64'
          pyinstaller_ver: '==6.11.1'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'MihoyoBBSTools'
          options: --onefile, --name "MihoyoBBSTools" 

  release:
    runs-on: ubuntu-latest
    needs:
      - pyinstaller-windows-x64-build
      - pyinstaller-linux-arm64-build
      - pyinstaller-linux-amd64-build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/MihoyoBBSTools-windows-x64/MihoyoBBSTools.exe
          asset_name: MihoyoBBSTools-windows-x64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Assets (Linux ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/MihoyoBBSTools-linux-arm64/MihoyoBBSTools
          asset_name: MihoyoBBSTools-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets (Linux AMD64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/MihoyoBBSTools-linux-amd64/MihoyoBBSTools
          asset_name: MihoyoBBSTools-linux-amd64
          asset_content_type: application/octet-stream                 