name: PyInstaller Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  pyinstaller-windows-x64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller==6.11.1

      - name: Build Executable
        run: pyinstaller --onefile --name "MihoyoBBSTools" main.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MihoyoBBSTools-windows-x64
          path: dist/MihoyoBBSTools.exe

  pyinstaller-linux-arm64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller==6.11.1

      - name: Build Executable
        run: pyinstaller --onefile --name "MihoyoBBSTools" main.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MihoyoBBSTools-linux-arm64
          path: dist/MihoyoBBSTools

  pyinstaller-linux-amd64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller==6.11.1

      - name: Build Executable
        run: pyinstaller --onefile --name "MihoyoBBSTools" main.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MihoyoBBSTools-linux-amd64
          path: dist/MihoyoBBSTools

  release:
    runs-on: ubuntu-latest
    needs:
      - pyinstaller-windows-x64-build
      - pyinstaller-linux-arm64-build
      - pyinstaller-linux-amd64-build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset (Windows x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/MihoyoBBSTools-windows-x64/MihoyoBBSTools.exe
          asset_name: MihoyoBBSTools-windows-x64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Linux ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/MihoyoBBSTools-linux-arm64/MihoyoBBSTools
          asset_name: MihoyoBBSTools-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Linux AMD64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/MihoyoBBSTools-linux-amd64/MihoyoBBSTools
          asset_name: MihoyoBBSTools-linux-amd64
          asset_content_type: application/octet-stream
